<head>
    <link rel='stylesheet' type="text/css" href='/resources/system/acp_style.css' />
    <link rel='stylesheet' type="text/css" href='/resources/system/monokai.css' />
    <link href="https://cdn.quilljs.com/1.3.5/quill.snow.css" rel="stylesheet">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="/images/favicon/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/images/favicon/favicon.ico" type="image/x-icon">
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous">
    </script>
    <script>
        $(document).ready(function () {
            setNavigation();
        });

        function setNavigation() {
            var path = window.location.pathname;
            path = path.replace(/\/$/, "");
            path = decodeURIComponent(path);

            $(".horizontal-menu a").each(function () {
                if (!$(this).hasClass("cinchme")) {
                    var href = $(this).attr('href');
                    if (path.indexOf(href) !== -1) {
                        $(this).closest('a').addClass('active');
                        document.title = $(this).attr('data-title');
                    }
                }
            });
            $(".left-menu a").each(function () {
                var href = $(this).attr('href');
                if (path.indexOf(href) !== -1) {
                    $(this).closest('a').addClass('active');
                    document.title = $(this).attr('data-title');
                }
            });
        }
    </script>
</head>
<body>
<div class="horizontal-menu">
    <ul>
        <li><a class="cinchms" href="/<?php echo $this->escape($this->admin_path)?>/dashboard" style="padding: 0;">Cinch<font color="#fff">MS</font></a></li>
        <li><a href="/<?php echo $this->escape($this->admin_path)?>/dashboard" data-title="Dashboard - CinchMS">Dashboard</a></li>
        <li><a href="/<?php echo $this->escape($this->admin_path)?>/articles" data-title="Articles - CinchMS">Articles</a></li>
        <li><a href="/<?php echo $this->escape($this->admin_path)?>/users" data-title="Users management - CinchMS">Users Management</a></li>
        <li style="float:right"><a href="/<?php echo $this->escape($this->admin_path)?>/authentication/logout" data-title="Logout - CinchMS">Logout</a></li>
        <li style="float:right"><a href="/<?php echo $this->escape($this->admin_path)?>/me" data-title="<?php echo $this->escape($this->username)?> - CinchMS"><?php echo $this->escape($this->username)?></a></li>
    </ul>
</div>
